### ISSUE TITLE
New install defaults to Russian 

### ISSUE THREAD

**Issue by Dweezledap** [PRO100BYTE/ProjectArcade#14]
After install I had to change "projectarcade.ini" from read only and modify the line:
LanguageDetection=0 to LanguageDetection=1
After restarting the app, it was now in English.

**Comment by TheDayG0ne** [comment]
The projectarcade.ini file is set to read-only when installed. As for the default language, I will fix it in the next release.

**Comment by DealsBeam** [comment]
How do I change the language to English?

**Comment by TheDayG0ne** [comment]
> How do I change the language to English?

Hi! This is a bug that occurred when building ProjectArcade. To temporarily fix it, you can remove the "Read-only" attribute from the projectarcade.ini file, change the LanguageDetection parameter in it by specifying 1 and save the file by returning the attribute back. After that, launch ProjectArcade using the shortcut. This error will be fixed in the new version of ProjectArcade.

My proposed option with changing the parameter value in the config is a temporary, but working solution.
